### PR TITLE
EarthClouds_HR pixelization fix

### PR DESCRIPTION
**Pull request by KvaNTy**
Ingame3
Hi @PhineasFreak. I've took 10k cloud textures from what's left of E.T.O, resized them to 8192x8192 and softened [abrupt transitions](https://i.imgur.com/QmYQ8Wj.png) where I could find them.

Here is side-by-side comparison of same 800x800 texture fragments at 100% scale(current on the left): [Source1](https://i.imgur.com/msy5T81.png), [Source2](https://i.imgur.com/1RaDnsV.png), [Source3](https://i.imgur.com/Z7Cq1h3.png), [Source4](https://i.imgur.com/SBpoSsi.png)
Clouds have somewhat sharper "endings" because of higher image contrast, probably due to some differences in how cubemaps were originally made.

And this is how these changes look from 200km orbit: [Ingame1](https://i.imgur.com/m4iXaFV.png), [Ingame2](https://i.imgur.com/hRdeYXL.png), [Ingame3](https://i.imgur.com/5sEzSqZ.png), [Ingame4](https://i.imgur.com/TrsUOmt.png)

### CODE REVIEW

**Comment by PhineasFreak** [comment]
I have already fixed them in my local branch. The cause were the .dds mipmaps applying incorrectly (for some reason the other cloud textures do not have that problem - maybe because of the resolution). I have also fixed my cubemap exporter since it tended to add seams to the texture edges and the final result was...sub-par at best.

I hope that i will also be able to fix some major "build-in" seams that do not appear in the lower resolution (8K) NASA cloud map.

**Comment by KvaNTy** [comment]
That's good news. Clouds without this fog around them look a bit less natural.
EarthCloudsZn had the most issues with weird transitions. Also I remember seen one such random transition in the middle of normal cloud area from orbit, but sadly I could not locate that spot in any .dds.

Are you planning to release update soon?

**Comment by PhineasFreak** [comment]
There are two very visible seams in the 21K NASA cloud map, one along the entire length of the texture (black line) and one one the left of the texture (mismatched clouds). The first one is easy to fix but the second will require some heavy editing to make sure that the overall quality is not degraded.

They are difficult to spot inside an image editor since the high resolution requires large zoom values in order to make them visible. KSP is a different case since the textures are mapped over a huge surface area (over 510000 km2) and any small imperfection will appear very easily in-flight.

Yes, i am planning to release a new version to fix most (if not all) of these bugs. It will also reduce the overall size of the package, both for the LR and HR versions.

**Comment by KvaNTy** [comment]
Oh, I see, original has same issues. Looks like more often clouds are not as mismatched as have sudden drops in resolution. Especially far from equator.

But it seems these locations follow a pattern, at least on complete globe image. Might be difficult to spot when it is in six different pieces though. Do you edit entire original texture first, or resulting cubemaps one by one?

**Comment by KvaNTy** [comment]
Well then, if you need help with editing I can take a look. In any case looking forward to next update.

**Pull request closed without merging**
