### PR TITLE
Theysen | Scatterer additions / configs for Earth & Mars

### PR DESCRIPTION
**Pull request by Theysen**
** I though I created a new branch - sorry. ** 

** Handle it as a demonstration addition at the time being ** 

- all .halfs are based off standard atmosphere data to have a realistic impression and feeling
- didn't see any strange behaviour throughout the climb to orbit, clouds appear normal as well

- added base Mars configs since current one is almost not visible around the surface

### CODE REVIEW

**Comment by PhineasFreak** [comment]
Very nice! Although they seem a bit overexposured but it may be just that my monitor is not correctly calibrated...

Cannot comment on the cloud fade issue as i did not experience it before.

Feel free to change anything else that you want. These two are definitely getting in for the next release candidate!

**Comment by Theysen** [comment]
There is room for change of course. I will slightly reduce the exposure values in the atmosphere, from orbit I think it looks quite accurate to pictures. I had old screenshots and they seemed less exposured to me in contrast to 1.2.2. Maybe something changed in the shaders / rendering / I also got a new display device since then.

Will test it, happy to help.

**Comment by PhineasFreak** [comment]
Blackrack changed the way scatter was rendered in version 0.0256 i think and it required a bit of fiddling to get the same visuals as before.

Yep, these parameters. Sorry for not clarifying it better. Ground reflectance controls the brightness of the ground/lower parts of the atmosphere

Mie, apart from modifying the ground scatter density, also controls the size of the apparent sun flare as seen from the surface (because of that density). The stock Scatterer parameters (0.004) make this flare cover almost half of the sky! Tested this yesterday with 0.002 and it seemed a bit better (Sun was again viewed as a semi-disk). I think something between 0.002 and 0.003 might do the job. The "develop" branch has a sample config implementing that if you want to take a look.

I am afraid of these Scatterer fade bugs because they do not manifest for my install and so i cannot resolve them by my own. Thank you for helping me out with this!

**Comment by Theysen** [comment]
I toned down the map view as there is no real hard difference when switching to Map View between 0.2 and 0.15. I did this to have a little more contrast on the orbit lines against the blue background when over waters. 

Please elaborate what you mean with 0.7 Exposure for Earth? Post Processing Exposure or Sky/Orbit or Rim/Orbit? Seems a little high to me and tests confirm a very overexposed surface / atmo.



Mars values are nice, really digging the darker look. I figured the ground textures are brighter due to RSSVE? Anyways, Mars needs another pass for a full ascent to see if the transitions are smooth with the new darker look, will push it when I am done. The issue I had is better with less exposed rims and atmo. 


To be precise on the clouds fade issue: THERE IS NONE. I don't know what people are seeing or describing.

**Comment by PhineasFreak** [comment]
Again, i should write what i think better...sorry!

For the Earth exposure i meant the sky "mapExposure" parameter that controls the overall exposure. Currently it has the value "1" but i found it too washed out (compared to various Earth images and in-game). Experimenting with the new configs i found that a value between 0.6 and 0.8 gives some nice results! And without the need to modify anything else.

There are some patches that modify the Kopernicus ambient and light color and intensity, along with the apparent light wavelength from the surface.

So, you mean that even with my old configs there was not "cloud fade" issue? Many users have reported that problem for various visual packs (SVE, GPP, SSRSS) but i wasn't sure if i had done something really bad.

If you are OK with the Earth exposure value that i mentioned i will make a new RC to get some feedback (and see if that fade bug is fixed/improved).

**Comment by Theysen** [comment]
Again, no problem!

Do you want me to make a final commit for the Earth stuff? I will check it out right now and see what it looks like.

**Comment by PhineasFreak** [comment]
I will selectively merge the Earth stuff and leave the Mars for the time being. But i think that this will need a separate "Mars PR" in the future to keep it clear from the rest of the configs.

**Comment by Theysen** [comment]
Indeed.

I am uploading a little video of an ascent to mark down some issues, especially with the city lights. And to show that there is no cloud fade issue. The city lights go bonkers when passing the magic 160km, and I don't know if this an issue with scatterer or general PQS / Scaled Space loading.

**Comment by PhineasFreak** [comment]
Oh...that might be **the** problem! Everyone has problems with the EVE city lights, ranging from fading to...Moon & Mars cities. Just check the latest RSS/RO/RP-0 video of Tyler Raiz.

Unfortunately that is a problem with EVE/Scatterer interop and i do not think that i can do something about it. That problem can also be seen on Venus and Titan with their cloud layers: land something to the surface and move the camera to force a PQS/SS transition. You will see the clouds suddenly get darker and the Scatterer rim configs almost disappear. I have pinpointed that to the alpha channel value of the global cloud texture (reducing the value to be near transparent fixes it but then they are not Venus and Titan anymore).

I could open a new issue for both Blackrack Waz to check and and add a reference to your demonstration video.

**Comment by Theysen** [comment]
https://www.youtube.com/watch?v=KJTfHeveNSs

Starting at one minute for the transitions. The city lights shine through at a 100% and then vanish, then reappear.

**Comment by PhineasFreak** [comment]
> I think it's relicts from the dated city lights code or artifacts with new scatterer features.

Yep, bad interactions of the city lights with Scatterer. I do not think that i has ever been reported so anything can be wrong with them. But, city lights have been broken since the EVE overhaul.

I will push the RC2 in a moment and add the city light interaction as another "known issue" with EVE.

**Comment by PhineasFreak** [comment]
Forgot to ask: do you want to keep this open and manually merge the Mars changes or do you want to create a new PR with them in the future?

**Comment by Theysen** [comment]
I'd say close this one and I get back at you with a new Mars PR / conversation.

**Comment by PhineasFreak** [comment]
Ok, you got it.

**Pull request closed without merging**
